### ISSUE TITLE
Create a dashboard on blockchain activity

### ISSUE THREAD

**Issue by posix4e** [hCaptcha/hmt-job-launch#4]
A simple js interface

1. Number of people paid
2. Number of jobs launched/completed
3. Active jobs
4. Total number of wallets

**Comment by excerebrose** [comment]
@uivlis maybe this is linked to your spreadsheet task?

**Comment by excerebrose** [comment]
[Dashboard Repository](https://github.com/hCaptcha/dashHMT)
